### ISSUE TITLE
A sample app?

### ISSUE THREAD

**Issue by tomekwi** [julbaxter/dataflow#2]
Hi,

to me this repo looks really interesting – but I can't find docs or any example of a running app. Have you got something of this kind?

Regards

**Comment by julbaxter** [comment]
Hi,

I just created a [repo](https://github.com/julbaxter/dataflow-examples) with some examples. Documentation will come soon. 
Thank you for your interest.

Regards

**Comment by tomek-he-him** [comment]
Many thanks!
